CREATE SEQUENCE alohandes_sequence;

CREATE TABLE EMPRESA(
	IDOPERADOR NUMBER,
	TIPOIDENTIFICACION VARCHAR2(20) NOT NULL,
	NOMBRE VARCHAR2(20) NOT NULL,
	REGISTROCAMARA VARCHAR2(20) NOT NULL,
	TIPODEALOJAMIENTO VARCHAR2(20) NOT NULL,
	CONSTRAINT EMPRESA_PK PRIMARYKEY(IDOPERADOR)
	
)

CREATE TABLE VECINO(
	IDOPERADOR NUMBER,
	TIPOIDENTIFICACION VARCHAR2(20) NOT NULL,
	NOMBRE VARCHAR2(20) NOT NULL,
	UBICACION VARCHAR2(20) NOT NULL,
	CONSTRAINT VECINO_PK PRIMARYKEY(IDOPERADOR)
)

CREATE TABLE ADMINVIVIENDA(
	IDOPERADOR NUMBER,
	TIPOIDENTIFICACION VARCHAR2(20) NOT NULL,
	NOMBRE VARCHAR2(20) NOT NULL,
	UBICACION VARCHAR2(20) NOT NULL,
	CONSTRAINT ADMINVIVIENDA_PK PRIMARYKEY(IDOPERADOR)
)

CREATE TABLE PROPIETARIOMIEMBRO(
	IDOPERADOR NUMBER,
	TIPOIDENTIFICACION VARCHAR2(20) NOT NULL,
	NOMBRE VARCHAR2(20) NOT NULL,
	UBICACION VARCHAR2(20) NOT NULL,
	TIPOMIEMBRO VARCHAR(20) NOT NULL,
	CONSTRAINT PROPIETARIOMIEMBRO_PK PRIMARYKEY(IDOPERADOR)
)

CREATE TABLE OFERTACOMUN(
	IDOFERTACOMUN NUMBER,
	CONSTRAINT OFERTACOMUN_PK PRIMARYKEY(IDOFERTACOMUN)
)
CREATE TABLE CLIENTE(
	IDCLIENTE NUMBER,
	NOMBRE VARCHAR2(20) NOT NULL,
	CORREO VARCHAR2(40) NOT NULL,
	CONSTRAINT CLIENTE_PK PRIMARYKEY(IDCLIENTE)
)
CREATE TABLE OFERTAEXCLUSIVA(
	IDOFERTAEXCLUSIVA NUMBER,
	CONSTRAINT OFERTAEXCLUSIVA_PK PRIMARYKEY(IDOFERTAEXCLUSIVA)
)